### ISSUE TITLE
NumPy Requirement Too Strict

### ISSUE THREAD

**Issue by alanhdu** [conda-forge/statsmodels-feedstock#25]
Right now, the current Linux build of `statsmodels=0.11.1` requires `numpy >=1.18.1,<2.0a0` (pulled from https://anaconda.org/conda-forge/statsmodels/0.11.1/download/linux-64/statsmodels-0.11.1-py36h516909a_0.tar.bz2). I think that requirement's too strict though: AFAICT, `statsmodels` shoul dsupport `numpy >= 1.15` (see https://github.com/statsmodels/statsmodels/blob/master/requirements.txt#L1).

I don't know what the right way to fix this is though: I can't even see where the `numpy >= 1.18.1` requirement comes from in this repo!

**Comment by ocefpaf** [comment]
The problem is in the recipe: https://github.com/conda-forge/statsmodels-feedstock/blob/master/recipe/meta.yaml#L23

That will force latest numpy to be used and then, to ensure ABI compatibility, it will be the lower limit. We need change >= 1.14 to 1.15. Do you want to send a PR  to fix that?

**Comment by alanhdu** [comment]
@ocefpaf: I'm not sure I quite understand -- should that be a ` >= 1.15` or should that become a ` = 1.15`?

If it's the latter, I opened up a PR at https://github.com/conda-forge/statsmodels-feedstock/pull/26 -- happy to revise if I misunderstood though!

**Comment by ocefpaf** [comment]
> @ocefpaf: I'm not sure I quite understand -- should that be a ` >= 1.15` or should that become a ` = 1.15`?

`>=1.15` will have have the same problem, latest `numpy` will be used. We need to be sure 1.15 is used to build, an old enough numpy, that any numpy that comes after it can use.

> If it's the latter, I opened up a PR at #26 -- happy to revise if I misunderstood though!

Thanks! All that was missing was the re-render. I called the bot to do that for us.
