### ISSUE TITLE
Numpy version pinned to the patch level

### ISSUE THREAD

**Issue by will133** [conda-forge/statsmodels-feedstock#27]
Issue:
It seems like the pinning of numpy is based on the patch level.  Therefore, it depends on the numpy version that this pulling from build time.  For instance, if the build is pulling in 1.5.4, it will force all the environment that tries to install this to use numpy 1.5.4, even though the environment may not want to or has a higher patch level of numpy.  For instance, if you have environment like:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
...
numpy                     1.15.2          ...
...
```
</details>

After I try to install statsmodels 0.11.1, it forces it to upgrade to 1.15.4:

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
...
          conda version : 4.6.14
    conda-build version : 3.18.10
         python version : 3.7.5.final.0
...
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/3.7.5 Linux/3.10.0-957.21.2.el7.x86_64 rhel/7.6 glibc/2.17
...
           offline mode : False

```
</details>

The reason is that this in recipe/meta.yaml:

```
  run:
    - python
    - {{ pin_compatible('numpy') }}
```
The pin by default would use a patch level.  It may be better to do this instead:

```
{{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
```

Doing this will pin to numpy 1.5.x instead of 1.5.4, which is more flexible if the code would work with numpy with the same minor version instead of the patch version.

**Comment by hmaarrfk** [comment]
I think this can now be closed.
